// English text pack — the reference copy. All written content and rules come
// from the Claude Design prototype (the .dc.html file under
// claude-design/project/) — keep in sync with it. content.zh.ts mirrors this
// file; when adding or changing lines here, update the Chinese pack too.
import type { TextPack } from './content';

export const EN: TextPack = {
  // Daily draw pool — always offline-safe (drawn locally, never the LLM).
  // The first 10 come from the design prototype; the rest are app-side
  // additions so there's real variety before the cycle repeats.
  daily: [
    { m: "You've survived 100% of your bad days. Undefeated, actually.", t: 'f' },
    { m: 'Small steps still count. Even tiny potato steps.', t: 'w' },
    { m: "Drink some water. You're a fancy plant with feelings.", t: 'f' },
    { m: "It's okay to do it badly first. That's called learning.", t: 'w' },
    { m: 'Rest is productive. Signed, a potato.', t: 'f' },
    { m: "You don't have to bloom today. Just stay rooted.", t: 'w' },
    { m: 'Done beats perfect. Perfect never ships.', t: 'f' },
    { m: 'Someone smiles when your name comes up. Promise.', t: 'w' },
    { m: 'Feelings are visitors. Tea, then they go.', t: 'w' },
    { m: 'Unclench your jaw. Drop your shoulders. There — better.', t: 'f' },
    { m: "You can't pour from an empty spud. Refill first.", t: 'f' },
    { m: "Progress hides in boring days. You're making some.", t: 'w' },
    { m: 'One thing at a time. Then the next thing.', t: 'w' },
    { m: 'Being gentle with yourself counts as an accomplishment.', t: 'w' },
    { m: 'The bad mood is weather, not climate. It passes.', t: 'w' },
    { m: "You don't need to earn your rest. Take it.", t: 'f' },
    { m: 'Comparison is a thief. Lock the door on it.', t: 'w' },
    { m: 'Half-done is still further than not-started.', t: 'w' },
    { m: "Breathe in for four. Out for four. I'll wait.", t: 'f' },
    { m: "Your worth isn't a to-do list. It never was.", t: 'w' },
    { m: "You're doing better than the voice in your head says.", t: 'w' },
    { m: "Tiny wins are still wins. I'm counting them.", t: 'f' },
    { m: 'You can start over at any hour. Even this one.', t: 'w' },
    { m: 'Soft days are for growing roots, not showing bloom.', t: 'w' },
    { m: "Plot twist: you're the main character. Act like it.", t: 'w' },
    { m: "You're not behind. You're on your own timeline. It's fashionable.", t: 'w' },
    { m: 'Even a couch potato is still a potato with dreams.', t: 'f' },
    { m: "You've survived every Monday so far. Basically a superhero.", t: 'f' },
    { m: "Perfectionism called. I hung up. You're welcome.", t: 'f' },
    { m: 'Water. Snack. Deep breath. In that order. Go.', t: 'f' },
    { m: 'You are allowed to be a work in progress and a masterpiece at once.', t: 'w' },
    { m: 'Bad day? Same you, fresh potato tomorrow.', t: 'f' },
    { m: "The to-do list survives one nap. I've tested this personally.", t: 'f' },
    { m: 'You bring something no algorithm can replace. Weird, warm you.', t: 'w' },
    { m: 'Growth is quiet. Nobody hears a potato getting wiser underground.', t: 'w' },
    { m: "Nobody has it all figured out. We're all just bluffing warmly.", t: 'f' },
    { m: "You got out of bed today. That's a certified boss move.", t: 'f' },
    { m: 'Your feelings are valid. Even the messy 3am ones. Especially those.', t: 'w' },
    { m: 'Confidence is just courage that stayed for breakfast.', t: 'w' },
    { m: "You're doing life for the first time. Cut yourself some slack.", t: 'w' },
    { m: 'A past version of you is so proud you made it here.', t: 'w' },
    { m: "Rest isn't quitting. It's recharging the main character.", t: 'f' },
    { m: 'You are 60% water and 100% doing your best. Great chemistry.', t: 'f' },
    { m: 'Showing up was the brave part. You already did it. Counts.', t: 'w' },
    { m: "You can't ruin a whole day. Reset the moment, not the mood.", t: 'w' },
    { m: "Be the reason you smile. Backup plan: I'm right here.", t: 'f' },
    { m: 'Mistakes mean you tried. Blank pages never got anything right either.', t: 'w' },
    { m: 'You are softer than you think and stronger than you feel.', t: 'w' },
    { m: 'Take the compliment. I said what I said. You are wonderful.', t: 'f' },
    { m: 'Your only job right now is the next small right thing.', t: 'w' },
    { m: "Tomorrow's a fresh spud. Nothing carries over but the love.", t: 'f' },
    { m: "Even mashed, you're still 100% potato. Nothing can un-potato you.", t: 'f' },
    { m: "You're somebody's reason to keep going. Probably mine.", t: 'w' },
    { m: "You matter on the days you can't feel it. I stitched this one slow so it holds.", t: 'w' },
    { m: "You've been someone's safe place. Today, let this card be yours.", t: 'w' },
    { m: "You're not too much and never too little — the exact right amount of you.", t: 'w' },
    { m: 'The bravest thing you did was keep going quietly. I noticed. I always do.', t: 'w' },
    { m: "You carried a lot today and you're still standing. That's the whole miracle.", t: 'w' },
    { m: 'You did the quiet, hard, unseen things today. I saw them. They counted.', t: 'w' },
    { m: "Some days you just endure. That's not nothing — that's the whole job, done.", t: 'w' },
    { m: "I don't say this lightly, and I mean it plain: I'm proud of you.", t: 'w' },
  ],

  poke: [
    'boing!',
    'hehe. again.',
    "I'm 90% stuffing, 10% courage.",
    'careful — I bruise emotionally.',
    '*wiggles menacingly*',
    'all of me is the soft spot.',
  ],

  // Body-poke flavor after you've already drawn — nudges toward another pull.
  retap: [
    "psst — the card's got more where that came from. tap away.",
    "another one? i've got a whole basket. help yourself.",
    "the good ones don't run out. tap the card again, go on.",
    "oh, you want seconds? i love that about you. tap away.",
    "infinite pep, one tap at a time. i don't tire. do you?",
    "there's always another card. the potato provides.",
  ],

  // Bubble shown when a normal (non-golden) card is revealed — random each draw.
  drawLines: [
    "here's one, fresh off the vine.",
    "ta-da. this one found you.",
    "picked this one just for now — it's yours.",
    "fresh card, still warm. here.",
    "ooh, nice pull. keep it, or tap for another.",
    "this one had your name on it.",
  ],

  cardHint: "today's card is ready — the white one. give it a tap. ♥",
  sedentary: '90 minutes in that chair! Even potatoes roll over sometimes. Stretch with me?',
  nightMsg: "It's past 11. The world can wait till morning. Sleep, dear human.",
  landing: 'wheee— ok. landing.',

  weaveLines: [
    'knitting a card just for you…',
    'picking the right words…',
    'tying the golden knot…',
  ],

  // Per-character chat fallback — warm in-voice "I'm here, keep going" lines
  // that fit any message without pretending to understand it.
  chatFallback: {
    spud: [
      "mm. i'm listening. i cleared my whole schedule for this — it was already empty, but still.",
      "i hear you. take your time; i've got nowhere else to be.",
      "that lands. keep going — i'm not going anywhere. literally. look at me.",
      "i'm right here with you. no rush, no fixing — just here.",
      "go on, i'm all ears. well — all eyes. potato thing.",
    ],
    taco: [
      "ok i'm LISTENING listening. spill it, i've got snacks and full attention.",
      "tell me everything, i'm basically a very supportive burrito right now.",
      "mmhm mmhm keep going — you've got my whole crunchy little heart here.",
      "i'm nodding so hard. lay it on me, all of it, every crumb.",
      "ooh, a feelings buffet? load me up. i'm here for every bite.",
    ],
    donut: [
      "aw, i'm listening, sugar. go on, tell me what's on that sweet mind.",
      "mm-hm, honeybun, i'm right here. let it all out, no judgment. hee.",
      "talk to me, love. i've got all the time in the world for you.",
      "keep going, sweetheart. every word of yours is worth hearing.",
      "i'm here, sugarplum. tell me more — i'm hanging on every bit.",
    ],
    bloom: [
      "i'm here. say it slowly, like watering. i'm listening.",
      "mm. let it out, little one. i have all the quiet you need.",
      "i hear you. no need to say it perfectly — just let it grow.",
      "keep going, softly. i'm rooted right here beside you.",
      "tell me more. some things need saying twice; i won't mind.",
    ],
    mochi: [
      "i'm right here, listening. tell me everything — no rush at all.",
      "ooh go on, i'm all ears. whatever it is, we've got it together.",
      "mm-hm, keep going. i'm not going anywhere, promise.",
      "tell me more! i'm hanging on every little bit.",
      "i'm here. say it however it comes out — i've got you.",
    ],
    grad: [
      "i'm listening — with, i'll note, my full and undivided attention. go on.",
      "mm. tell me more. my research improves considerably with additional data.",
      "noted for the record. continue; i find this genuinely worth my time.",
      "i'm here, and i'm paying attention. that is the whole syllabus today.",
      "say more. per long observation, most things feel lighter once said aloud.",
    ],
  },

  // Generic chat fallback — the last resort when the LLM can't be reached.
  fallbackReply: "mm — I'm listening. tell me a bit more?",

  // Shown when the day's real-time chat budget is spent (server returns 429) —
  // warm "let's pick this up tomorrow" lines so the cap never feels like an error.
  chatLimit: {
    spud: "that was a lot of good talking for one day. i'm going to go stare at the wall and process — same time tomorrow?",
    taco: "ok my little brain is FULL of feelings for one day. same time tomorrow? i'll bring snacks.",
    donut: "sugar, i've been chatting my glaze off — let me rest my sprinkles and we'll talk more tomorrow, hm?",
    bloom: "we've watered enough words today. let them settle overnight; i'll be right here tomorrow.",
    mochi: "we did so much good talking today. let's let it settle and pick it up again tomorrow — i'll be right here, bouncy as ever.",
    grad: "per my notes, we've reached today's word quota. the research resumes tomorrow. class dismissed, warmly.",
  },

  pers: {
    spud: {
      p: 'warm & witty',
      hi: {
        morning: "Morning. Card's warm — I sat on it all night. Tap me.",
        afternoon: "Afternoon. Card's still warm — been keeping it for you. Tap me.",
        evening: "Evening. Card's warm — I saved it for when you got in. Tap me.",
        night: "Late one. Card's warm — I kept it lit for you. Tap me.",
      },
    },
    taco: {
      p: 'unhinged pep',
      hi: {
        morning: 'GOOD MORNING. ok, that was loud. hi. tap me?',
        afternoon: "afternoon! you made it half the day, that's basically a whole taco. tap me?",
        evening: 'EVENING. day’s cooling off, come grab a warm one. tap me?',
        night: "psst, it's late. one tiny midnight-snack card? tap me?",
      },
    },
    donut: {
      p: 'sugar rush',
      hi: {
        morning: 'morning, sugar! got something sweet for you.',
        afternoon: 'afternoon, honeybun! saved you a little sugar. hee.',
        evening: "evening, sugar. come unwind — I've got something sweet.",
        night: 'still up, sugar? one sweet little thing before bed, hee.',
      },
    },
    bloom: {
      p: 'soft nurture',
      hi: {
        morning: 'good morning. the flowers asked about you.',
        afternoon: "afternoon. the garden's warm — did you drink some water?",
        evening: 'evening. the light’s going soft. how was your day?',
        night: "it's late. even the garden's asleep. shall we rest too?",
      },
    },
    mochi: {
      p: 'bouncy cheer',
      hi: {
        morning: "morning! fresh card, fresh bounce — come see? ♡",
        afternoon: "halfway there and you're doing great. today's card is a bright one — tap me?",
        evening: "evening! you made it through the whole day. this card's a happy one — tap me?",
        night: "still up? one soft little card, then let's rest. you did enough today.",
      },
    },
    grad: {
      p: 'dry wisdom',
      hi: {
        morning: "ah, awake. per my research, you'll want today's card.",
        afternoon: 'afternoon. my research indicates a card is overdue.',
        evening: "evening. the data suggests you've done enough. one card?",
        night: 'still up? my findings are conclusive: card, then sleep. tap me.',
      },
    },
  },

  unlock: {
    spud: null,
    taco: { verb: 'cards kept', how: 'keep 2 cards' },
    donut: { verb: 'favorites', how: 'mark 3 favorites in the Book' },
    bloom: { verb: 'heart-to-hearts', how: 'tell him 5 things' },
    mochi: { verb: 'day streak', how: 'reach a 3-day streak' },
    grad: { verb: 'golden cards', how: 'keep 3 golden cards' },
  },

  kindLabels: {
    work: 'Work',
    goal: 'Goals',
    people: 'People',
    pets: 'Pets',
    likes: 'Likes',
    milestone: 'Milestones',
    feeling: 'Feelings',
    other: 'Other',
  },

  // Built-in idle-mutter pools (brain.ts) — the potato's inner monologue.
  mutter: {
    watch: [
      'clack clack clack. look at them go.',
      'so focused today. proud. quietly.',
      "i'll supervise from here.",
      'that was a strong keystroke. felt it from here.',
      'important human business. do not interrupt. noted.',
      'they blinked. i blinked back. teamwork.',
    ],
    alone: [
      'counted my sprouts again. still three. consistency.',
      'do clouds get tired? note to self: ask a cloud.',
      "hm. that pixel wasn't there yesterday.",
      'quiet is nice. we like quiet.',
      "if i had knees, i'd stretch them.",
      "today's plan: sit. so far, flawless.",
      'i wonder what gravy dreams about.',
      'rearranged my card. big day.',
    ],
    lonely: [
      "they'll be back. they always come back.",
      'the cursor left. classic cursor.',
      'guarding the desk. nothing to report.',
      'i could learn to whistle. do i have lips? investigating.',
    ],
    sleepy: [
      'eyes are heavy… just resting them…',
      'not sleeping. thinking with my eyes closed…',
      'five more minutes…',
      'zz… mashed… no… whipped…',
      'the pixels are going soft…',
      'gonna rest my eyes. just the eyes.',
    ],
    ignored: [
      'noted. important human business.',
      "ok. filing this under 'later'.",
      "cool cool cool. i'll be right here.",
      'the knock economy is rough right now.',
    ],
    wake: [
      "i wasn't sleeping. i was thinking with my eyes closed.",
      'awake! was awake the whole time. mostly.',
      'mm. what year is it. ok good.',
      'dreamt i was a croissant. troubling.',
    ],
  },

  // Spoken lines for the brain's social beats (greet-back, knocking, delight).
  speak: {
    greet: [
      "oh! you're back. the desk is safe. i was very brave.",
      "you're back! nothing happened. except one dust bunny. it was huge.",
      'there you are. the chair missed you. i can tell.',
      'welcome back. i kept your pixels warm.',
    ],
    knock: [
      "knock knock. it's me. reason: none. just checking on you.",
      "hey. tiny check-in — water break? i'll wait.",
      "psst. shoulders down. they're not earrings.",
      "you've been at it a while. blink with me? one… two.",
      "quick survey: how's the human doing? one word is fine.",
    ],
    delight: [
      "you're here! hi. hello. ok. that's all i needed.",
      'worth it. carry on.',
      'ah, there you are. as you were.',
      "that's the stuff. ok. back to business.",
    ],
  },

  // Variant pools for the self-play routines' spoken steps (brain.ts ROUTINES).
  routines: {
    chaseStart: [
      'is that… my tail? hold on.',
      'something moved back there. suspicious.',
      'do i even have a tail? one way to find out.',
      'the tail. today is the day.',
    ],
    chaseEnd: [
      'conclusion: the tail remains theoretical.',
      'the tail wins again. respect.',
      'update: round on all sides. investigation ongoing.',
      "i'll catch it tomorrow. it knows i will.",
    ],
    juggleEnd: [
      'nailed it. nobody saw. still counts.',
      'gravity tried. i tried harder.',
      'flawless routine. the stapler seemed impressed.',
      'and the crowd goes… quiet. impressed quiet.',
    ],
    studyStart: [
      'card inspection time.',
      'daily card audit. very official.',
      'quality control. someone has to do it.',
    ],
    studyEnd: [
      'checked twice. still true.',
      'all words present and accounted for.',
      'inspection complete. no notes.',
      'hm. reads even better upside down.',
    ],
    practiceStart: [
      'rehearsal. gotta keep the wave sharp.',
      'wave drills. form is everything.',
      'practicing my wave. for waving emergencies.',
    ],
    practiceEnd: [
      'wave form: excellent. audience: none.',
      'that one had real wrist in it. if i had wrists.',
      'the follow-through needs work. the enthusiasm does not.',
    ],
    humEnd: [
      'that song has no words. perfect song.',
      "i made that one up. it's about soup.",
      'same three notes as yesterday. a classic now.',
    ],
    stretchEnd: [
      'ooh. heard a click. good click, i think.',
      'taller now. probably. by a little.',
      'stretching complete. i am basically elastic.',
    ],
    sneezeEnd: [
      '…dusty in here. excuse me.',
      '…startled myself. again.',
      'that one came from deep in the starch.',
    ],
  },

  ui: {
    tapMe: 'tap me :)',
    dayShort: (day) => `DAY ${day}`,
    careNight: 'NIGHT CARE',
    careStretch: 'STRETCH BREAK',
    todaysCardTag: "TODAY'S CARD",
    goldenTag: 'RARE · GOLDEN STITCH',
    keepIt: 'Keep it ♥',
    openTheBook: '♥ Open the Book',
    later: 'Later',
    thanks: (name) => `Thanks, ${name} ♥`,
    signDay: (name, day) => `— ${name} · day ${day}`,
    drawLabel: "today's card",
    weaveBrand: 'GOLDEN STITCH IN PROGRESS',
    anon: 'Anonymous',
    bookTitle: 'Card Book',
    tabCards: 'Cards',
    tabChat: 'Chat',
    tabMem: 'Memory',
    filterAll: 'all',
    filterGold: 'golden ✦',
    filterFav: 'favorites ♥',
    emptyCards: "No cards yet — tap your buddy for today's draw.",
    emptyGold: 'No golden cards yet — weave one.',
    emptyFav: 'No favorites yet — tap the ♥ on a card.',
    emptyChat: "No messages yet — say hi and he'll answer.",
    emptyMem: "Nothing here yet — the more you tell him about your life, the more he'll remember, and knit into your golden cards.",
    hintCards: 'your kept cards — clear them anytime',
    hintChat: "every word, kept — clearing wipes his context, not his memory of you",
    hintMem: 'his picture of you — unpick any stitch, anytime',
    memHead: "the quilt he's making of you — sunny patches and rainy ones, all kept",
    clearAll: 'clear all',
    knitTag: (label) => `knit into Memory · ${label}`,
    cardFoot: (day, by) => `day ${day} — ${by}`,
    dayDivider: (day, weekday) => `DAY ${day}${weekday ? ` · ${weekday}` : ''}`,
    memDay: (day) => `DAY ${day}`,
    weekdayLocale: 'en-US',
    buddiesTitle: 'Buddies',
    friendsCount: (n, total) => `${n}/${total} friends`,
    onDuty: 'On duty ♥',
    setActive: 'Set active',
    buddiesHint: 'each buddy joins for a different kind of care — keep · favorite · confide · show up · go gold. once a friend, always a friend',
    joinsWhen: (name, how) => `${name} joins when you ${how}.`,
    placeholder: (name) => `tell ${name} what's on your mind…`,
    tucked: 'Tucked into the Book. ♥',
    maybeNext: 'Maybe next time. ♥',
    holding: 'Holding this one for you. ♥',
    knitFresh: 'Knit fresh, just for you.',
    unlocked: (names) => `Unlocked: ${names}! Say hi in Buddies.`,
    settingsTitle: 'settings',
    langLabel: 'language',
    soundLabel: 'sound',
    soundOn: 'on',
    soundOff: 'off',
    immersiveLabel: 'focus mode',
    immersiveHint: 'he stays quiet & still while you work — no muttering, no antics, sound off',
    sizeLabel: 'size',
    sizeSmall: 'small',
    sizeMed: 'medium',
    sizeLarge: 'large',
  },
};
