// Curated English quote pool — famous lines from literary masters, novels,
// films, series and famous speeches, hand-picked to work as encouragement
// cards. Static content bundled with the app: the golden card's non-live
// source, always available (offline too). Shipping a new app build is the
// update flow.
//
// House rules for entries:
// - one short line each, warm/uplifting — it must read well on a tiny card
// - no song lyrics, no classical Chinese poetry (see quotes.zh.ts)
// - EVERY entry carries `s` — a real, specific attribution shown on the card;
//   keep it under ~24 chars so the card foot doesn't overflow. No Proverb /
//   Anonymous / internet shrug-labels: a line whose only honest tag is one of
//   those belongs in server/scripts/internet-lines.en.txt (the daily normal
//   pool draws from it), not in the golden pool.
// - attribution follows common usage, not scholarship — this pool is charm,
//   not a citation database
import type { Quote } from './types';

export const QUOTES_EN: Quote[] = [
  // ── films ──
  { q: 'After all, tomorrow is another day.', s: 'Gone with the Wind' },
  { q: "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.", s: 'Rocky Balboa' },
  { q: "Life is like a box of chocolates. You never know what you're gonna get.", s: 'Forrest Gump' },
  { q: 'Hope is a good thing, maybe the best of things, and no good thing ever dies.', s: 'Shawshank Redemption' },
  { q: 'Get busy living, or get busy dying.', s: 'Shawshank Redemption' },
  { q: 'Carpe diem. Seize the day. Make your lives extraordinary.', s: 'Dead Poets Society' },
  { q: "Don't ever let somebody tell you you can't do something.", s: 'Pursuit of Happyness' },
  { q: 'You want something? Go get it. Period.', s: 'Pursuit of Happyness' },
  { q: 'Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.', s: 'Kung Fu Panda' },
  { q: "There is no secret ingredient. It's just you.", s: 'Kung Fu Panda' },
  { q: 'Not everyone can become a great artist, but a great artist can come from anywhere.', s: 'Ratatouille' },
  { q: 'If you focus on what you left behind, you will never be able to see what lies ahead.', s: 'Ratatouille' },
  { q: 'Just keep swimming.', s: 'Finding Nemo' },
  { q: 'The past can hurt. But you can either run from it, or learn from it.', s: 'The Lion King' },
  { q: 'Remember who you are.', s: 'The Lion King' },
  { q: 'The flower that blooms in adversity is the most rare and beautiful of all.', s: 'Mulan' },
  { q: 'Have courage and be kind.', s: 'Cinderella' },
  { q: 'Even miracles take a little time.', s: 'Cinderella' },
  { q: 'Keep moving forward.', s: 'Meet the Robinsons' },
  { q: 'Ohana means family. Family means nobody gets left behind or forgotten.', s: 'Lilo & Stitch' },
  { q: 'All it takes is faith and trust.', s: 'Peter Pan' },
  { q: 'The very things that hold you down are going to lift you up.', s: 'Dumbo' },
  { q: 'Today is a good day to try.', s: 'Hunchback of Notre Dame' },
  { q: 'Do, or do not. There is no try.', s: 'Yoda, Star Wars' },
  { q: 'The Force will be with you. Always.', s: 'Star Wars' },
  { q: 'Never tell me the odds.', s: 'Han Solo, Star Wars' },
  { q: 'Why do we fall? So that we can learn to pick ourselves up.', s: 'Batman Begins' },
  { q: 'To infinity and beyond!', s: 'Toy Story' },
  { q: 'Adventure is out there!', s: 'Up' },
  { q: 'Thanks for the adventure. Now go have a new one.', s: 'Up' },
  { q: "You've always had the power, my dear. You just had to learn it for yourself.", s: 'The Wizard of Oz' },
  { q: "There's no place like home.", s: 'The Wizard of Oz' },
  { q: 'It is our choices that show what we truly are, far more than our abilities.', s: 'Harry Potter' },
  { q: 'Happiness can be found even in the darkest of times, if one only remembers to turn on the light.', s: 'Harry Potter' },
  { q: 'It does not do to dwell on dreams and forget to live.', s: 'Harry Potter' },
  { q: 'Even the smallest person can change the course of the future.', s: 'The Lord of the Rings' },
  { q: 'All we have to decide is what to do with the time that is given us.', s: 'The Lord of the Rings' },
  { q: "There's some good in this world, and it's worth fighting for.", s: 'The Lord of the Rings' },
  { q: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", s: "Ferris Bueller's Day Off" },
  { q: 'You is kind. You is smart. You is important.', s: 'The Help' },
  { q: 'Every passing minute is another chance to turn it all around.', s: 'Vanilla Sky' },
  { q: "Some people can't believe in themselves until someone else believes in them first.", s: 'Good Will Hunting' },
  { q: 'The only way to achieve the impossible is to believe it is possible.', s: 'Alice in Wonderland' },
  { q: "Have I gone mad? I'm afraid so. But let me tell you something: the best people usually are.", s: 'Alice in Wonderland' },
  { q: 'You solve one problem, and then the next. Solve enough problems, and you get to come home.', s: 'The Martian' },
  { q: 'We will find a way. We always have.', s: 'Interstellar' },
  { q: "We're all traveling through time together, every day of our lives.", s: 'About Time' },
  { q: "If we're kind and polite, the world will be right.", s: 'Paddington' },
  { q: "I'm going to live every minute of it.", s: 'Soul' },
  { q: 'Seize your moment.', s: 'Coco' },
  { q: "Life's a little bit messy. We all make mistakes.", s: 'Zootopia' },
  { q: 'Anyone can be anything.', s: 'Zootopia' },
  { q: "I don't want to survive. I want to live!", s: 'WALL·E' },
  { q: "In case I don't see ya: good afternoon, good evening, and good night!", s: 'The Truman Show' },
  { q: "Here's looking at you, kid.", s: 'Casablanca' },
  { q: 'No man is a failure who has friends.', s: "It's a Wonderful Life" },
  { q: "It's supposed to be hard. The hard is what makes it great.", s: 'A League of Their Own' },
  { q: 'If you build it, he will come.', s: 'Field of Dreams' },
  { q: 'If you put your mind to it, you can accomplish anything.', s: 'Back to the Future' },
  { q: "I'll be right here.", s: 'E.T.' },
  { q: 'First learn stand, then learn fly.', s: 'The Karate Kid' },
  { q: 'You must always have faith in yourself.', s: 'Legally Blonde' },
  { q: 'To see the world, and to feel — that is the purpose of life.', s: 'Walter Mitty' },
  { q: 'When life gets you down, you know what you gotta do? Just keep swimming.', s: 'Finding Nemo' },

  // ── series ──
  { q: 'Be curious, not judgmental.', s: 'Ted Lasso' },
  { q: 'Be a goldfish.', s: 'Ted Lasso' },
  { q: 'I believe in hope. I believe in believe.', s: 'Ted Lasso' },
  { q: 'Doing the right thing is never the wrong thing.', s: 'Ted Lasso' },
  { q: "I wish there was a way to know you're in the good old days before you've actually left them.", s: 'The Office' },
  { q: "You miss 100% of the shots you don't take.", s: 'Michael Scott, The Office' },
  { q: "We have to remember what's important in life: friends, waffles, and work.", s: 'Parks and Recreation' },
  { q: 'Treat yo self.', s: 'Parks and Recreation' },
  { q: "Welcome to the real world. It sucks. You're gonna love it.", s: 'Friends' },
  { q: "Nine hundred years of time and space, and I've never met anyone who wasn't important.", s: 'Doctor Who' },
  { q: "We're all stories in the end. Just make it a good one, eh?", s: 'Doctor Who' },
  { q: "It gets easier. Every day it gets a little easier. But you gotta do it every day — that's the hard part.", s: 'BoJack Horseman' },
  { q: 'Look for the helpers. You will always find people who are helping.', s: 'Fred Rogers' },
  { q: "You've made this day a special day, by just your being you.", s: 'Fred Rogers' },
  { q: 'There is no person in the whole world like you, and I like you just the way you are.', s: 'Fred Rogers' },
  { q: "What matters is if you're trying to be better today than you were yesterday.", s: 'The Good Place' },
  { q: 'The most amazing things that can happen to a human being will happen to you, if you just lower your expectations.', s: 'Modern Family' },
  { q: "There's no lemon so sour that you can't make something resembling lemonade.", s: 'This Is Us' },
  { q: "Whenever I'm sad, I stop being sad and be awesome instead.", s: 'How I Met Your Mother' },
  { q: "You can't always see the light at the end of the tunnel, but if you keep moving, you will come to a better place.", s: 'Uncle Iroh, Avatar' },
  { q: 'While it is always best to believe in oneself, a little help from others can be a great blessing.', s: 'Uncle Iroh, Avatar' },
  { q: 'Live long and prosper.', s: 'Star Trek' },
  { q: 'What is grief, if not love persevering?', s: 'WandaVision' },
  { q: "Friends don't lie.", s: 'Stranger Things' },

  // ── books ──
  { q: 'It is only with the heart that one can see rightly; what is essential is invisible to the eye.', s: 'The Little Prince' },
  { q: 'All grown-ups were once children — but only few of them remember it.', s: 'The Little Prince' },
  { q: 'What makes the desert beautiful is that somewhere it hides a well.', s: 'The Little Prince' },
  { q: "You're braver than you believe, stronger than you seem, and smarter than you think.", s: 'Winnie the Pooh' },
  { q: 'Sometimes the smallest things take up the most room in your heart.', s: 'Winnie the Pooh' },
  { q: 'The nicest thing about the rain is that it always stops. Eventually.', s: 'Winnie the Pooh' },
  { q: "Isn't it nice to think that tomorrow is a new day with no mistakes in it yet?", s: 'Anne of Green Gables' },
  { q: 'Dear old world, you are very lovely, and I am glad to be alive in you.', s: 'Anne of Green Gables' },
  { q: 'When you want something, all the universe conspires in helping you to achieve it.', s: 'The Alchemist' },
  { q: 'The secret of life is to fall seven times and to get up eight times.', s: 'The Alchemist' },
  { q: 'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.', s: 'Dr. Seuss' },
  { q: 'Today you are You, that is truer than true. There is no one alive who is Youer than You.', s: 'Dr. Seuss' },
  { q: 'Unless someone like you cares a whole awful lot, nothing is going to get better.', s: 'The Lorax' },
  { q: 'You have been my friend. That in itself is a tremendous thing.', s: "Charlotte's Web" },
  { q: "Real isn't how you are made. It's a thing that happens to you.", s: 'The Velveteen Rabbit' },
  { q: 'If you have good thoughts, they will shine out of your face like sunbeams.', s: 'Roald Dahl' },
  { q: "Those who don't believe in magic will never find it.", s: 'Roald Dahl' },
  { q: 'The moment you doubt whether you can fly, you cease for ever to be able to do it.', s: 'Peter Pan' },
  { q: 'To live will be an awfully big adventure.', s: 'Peter Pan' },
  { q: "It's no use going back to yesterday, because I was a different person then.", s: 'Alice in Wonderland' },
  { q: 'If you look the right way, you can see that the whole world is a garden.', s: 'The Secret Garden' },
  { q: 'I am no bird; and no net ensnares me: I am a free human being with an independent will.', s: 'Jane Eyre' },
  { q: 'I am not afraid of storms, for I am learning how to sail my ship.', s: 'Little Women' },
  { q: "Real courage is when you know you're licked before you begin, but you begin anyway.", s: 'To Kill a Mockingbird' },
  { q: "And now that you don't have to be perfect, you can be good.", s: 'East of Eden' },
  { q: "There's only one rule that I know of: you've got to be kind.", s: 'Kurt Vonnegut' },
  { q: 'Tell me, what is it you plan to do with your one wild and precious life?', s: 'Mary Oliver' },
  { q: "You don't have to understand life. You just have to live it.", s: 'The Midnight Library' },
  { q: 'You are still here. And that is everything.', s: 'Matt Haig' },
  { q: 'The world is not in your books and maps. It is out there.', s: 'The Hobbit' },
  { q: 'There is nothing half so much worth doing as simply messing about in boats.', s: 'Wind in the Willows' },
  { q: 'Almost everything will work again if you unplug it for a few minutes. Including you.', s: 'Anne Lamott' },
  { q: 'Courage starts with showing up and letting ourselves be seen.', s: 'Brené Brown' },
  { q: 'And in that moment, I swear we were infinite.', s: 'Perks of Being a Wallflower' },
  { q: 'You must take life the way it comes at you, and make the best of it.', s: 'Life of Pi' },
  { q: 'When given the choice between being right and being kind, choose kind.', s: 'Wonder' },
  { q: '"What do you want to be when you grow up?" "Kind," said the boy.', s: 'Charlie Mackesy' },
  { q: "Asking for help isn't giving up. It's refusing to give up.", s: 'Charlie Mackesy' },
  { q: 'One of our greatest freedoms is how we react to things.', s: 'Charlie Mackesy' },
  { q: 'I have never tried that before, so I think I should definitely be able to do that.', s: 'Pippi Longstocking' },

  // ── voices: speeches, letters, interviews ──
  { q: "Go confidently in the direction of your dreams. Live the life you've imagined.", s: 'Henry David Thoreau' },
  { q: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', s: 'Ralph Waldo Emerson' },
  { q: 'Be yourself; everyone else is already taken.', s: 'Oscar Wilde' },
  { q: 'We are all in the gutter, but some of us are looking at the stars.', s: 'Oscar Wilde' },
  { q: 'The secret of getting ahead is getting started.', s: 'Mark Twain' },
  { q: 'Kindness is the language which the deaf can hear and the blind can see.', s: 'Mark Twain' },
  { q: "Try to be a rainbow in someone's cloud.", s: 'Maya Angelou' },
  { q: 'You may not control all the events that happen to you, but you can decide not to be reduced by them.', s: 'Maya Angelou' },
  { q: 'People will never forget how you made them feel.', s: 'Maya Angelou' },
  { q: 'No one can make you feel inferior without your consent.', s: 'Eleanor Roosevelt' },
  { q: 'The future belongs to those who believe in the beauty of their dreams.', s: 'Eleanor Roosevelt' },
  { q: 'Do one thing every day that scares you.', s: 'Eleanor Roosevelt' },
  { q: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', s: 'Winston Churchill' },
  { q: "If you're going through hell, keep going.", s: 'Winston Churchill' },
  { q: 'It always seems impossible until it is done.', s: 'Nelson Mandela' },
  { q: 'Keep your face to the sunshine and you cannot see a shadow.', s: 'Helen Keller' },
  { q: 'Alone we can do so little; together we can do so much.', s: 'Helen Keller' },
  { q: 'The most effective way to do it, is to do it.', s: 'Amelia Earhart' },
  { q: "Don't count the days; make the days count.", s: 'Muhammad Ali' },
  { q: 'Stay hungry, stay foolish.', s: 'Steve Jobs' },
  { q: 'The only way to do great work is to love what you do.', s: 'Steve Jobs' },
  { q: "We don't make mistakes, just happy little accidents.", s: 'Bob Ross' },
  { q: "Talent is a pursued interest. Anything that you're willing to practice, you can do.", s: 'Bob Ross' },
  { q: "You're only given a little spark of madness. You mustn't lose it.", s: 'Robin Williams' },
  { q: "Nothing is impossible. The word itself says 'I'm possible'!", s: 'Audrey Hepburn' },
  { q: 'If you want the rainbow, you gotta put up with the rain.', s: 'Dolly Parton' },
  { q: 'Find out who you are and do it on purpose.', s: 'Dolly Parton' },
  { q: 'Storms make trees take deeper roots.', s: 'Dolly Parton' },
  { q: 'Do what you can, with what you have, where you are.', s: 'Theodore Roosevelt' },
  { q: 'Comparison is the thief of joy.', s: 'Theodore Roosevelt' },
  { q: "Believe you can and you're halfway there.", s: 'Theodore Roosevelt' },
  { q: 'Life is like riding a bicycle. To keep your balance, you must keep moving.', s: 'Albert Einstein' },
  { q: 'What would life be if we had no courage to attempt anything?', s: 'Vincent van Gogh' },
  { q: 'Great things are done by a series of small things brought together.', s: 'Vincent van Gogh' },
  { q: 'I have failed over and over and over again in my life. And that is why I succeed.', s: 'Michael Jordan' },
  { q: 'Never let the fear of striking out keep you from playing the game.', s: 'Babe Ruth' },
  { q: 'One child, one teacher, one book, one pen can change the world.', s: 'Malala Yousafzai' },
  { q: 'Talk to yourself like you would to someone you love.', s: 'Brené Brown' },
  { q: 'Done is better than perfect.', s: 'Sheryl Sandberg' },
  { q: 'Be somebody who makes everybody feel like a somebody.', s: 'Kid President' },
  { q: 'Tomorrow is the first blank page of a 365-page book. Write a good one.', s: 'Brad Paisley' },
  { q: 'Not every day is good, but there is something good in every day.', s: 'Alice Morse Earle' },
];
