// Daily card batch from the server (pre-generated by the Worker's cron).
// Draws pick from this pool locally — no real-time LLM call. When the server
// isn't configured or is unreachable, the pools stay null and callers fall back
// to the built-in offline content in content.js.
const pp = window.pp;

let BATCH = null; // { date, cards: { [charId]: { normal: string[], golden: string[] } } }

export async function refresh() {
  if (!pp || !pp.cards) return null;
  try {
    const data = await pp.cards.today();
    if (data && data.cards) BATCH = data;
  } catch (e) {
    // keep whatever we had (possibly null) — draws just use the local pool
  }
  return BATCH;
}

function poolOf(charId, tier) {
  const c = BATCH && BATCH.cards && BATCH.cards[charId];
  const arr = c && c[tier];
  return Array.isArray(arr) && arr.length ? arr : null;
}

// Today's normal-card lines for a character, or null → use the built-in DAILY.
export function normalPool(charId) {
  return poolOf(charId, 'normal');
}

// Today's golden-tier lines, used as the fallback when the personalized weave
// can't reach the LLM (offline or over the daily budget).
export function goldenPool(charId) {
  return poolOf(charId, 'golden');
}

// Today's fresh mutter pool for a mood (watch/alone/lonely), or null → the brain
// falls back to its built-in MUTTER lines. Zero real-time cost — pre-generated.
export function mutterPool(charId, mood) {
  const c = BATCH && BATCH.cards && BATCH.cards[charId];
  const m = c && c.mutters && c.mutters[mood];
  return Array.isArray(m) && m.length ? m : null;
}
