// Daily card batch from the server (pre-generated by the Worker's cron).
// Draws pick from this pool locally — no real-time LLM call. When the server
// isn't configured or is unreachable, the pools stay null and callers fall back
// to the built-in offline content in the language packs.
import { lang } from './locale';
import type { CardsBatch, CharId, Lang, MutterMood, Quote } from './types';

const pp = window.pp;

let BATCH: CardsBatch | null = null;
let batchLang: Lang | null = null;

// The server can answer in the wrong language — an out-of-date Worker ignores
// ?lang and serves the English batch for zh, and that answer may already sit
// in the per-language disk cache. Trust a batch only when its lines are
// actually written in the requested language: sample the shared normal pool
// plus the golden pools and check which script they're in.
function batchMatchesLang(batch: CardsBatch, want: Lang): boolean {
  const lines = [
    ...(Array.isArray(batch.normal) ? batch.normal : []),
    ...Object.values(batch.cards || {}).flatMap((c) => (c && Array.isArray(c.golden) ? c.golden : [])),
  ];
  if (!lines.length) return false; // empty batch — nothing usable in it anyway
  const cjk = lines.filter((s) => /[一-鿿]/.test(s)).length;
  return want === 'zh' ? cjk > lines.length / 2 : cjk <= lines.length / 2;
}

export async function refresh(): Promise<CardsBatch | null> {
  if (!pp || !pp.cards) return null;
  const want = lang();
  try {
    const data = await pp.cards.today(want);
    if (data && data.cards && batchMatchesLang(data, want)) {
      BATCH = data;
      batchLang = want;
    }
  } catch (e) {
    // keep whatever we had (possibly null) — draws just use the local pool
  }
  // a language switch mid-flight (or a failed fetch after one) leaves a
  // wrong-language batch behind — drop it so draws fall back to built-ins
  // rather than handing out cards in the old language
  if (BATCH && batchLang !== lang()) {
    BATCH = null;
    batchLang = null;
  }
  return BATCH;
}

// Date stamp of the loaded batch, or null before the first successful fetch.
// The app compares it across draws to reset its no-replacement bookkeeping
// when a fresh daily pool arrives.
export function batchDate(): string | null {
  return (BATCH && BATCH.date) || null;
}

function poolOf(charId: CharId, tier: 'normal' | 'golden'): string[] | null {
  const c = BATCH && BATCH.cards && BATCH.cards[charId];
  const arr = c && c[tier];
  return Array.isArray(arr) && arr.length ? arr : null;
}

// Today's normal-card lines — one shared voice-neutral pool for every
// character, or null → use the built-in DAILY. Falls back to the per-character
// field an older cached batch may still carry.
export function normalPool(charId: CharId): string[] | null {
  const shared = BATCH && BATCH.normal;
  if (Array.isArray(shared) && shared.length) return shared;
  return poolOf(charId, 'normal');
}

// The server's famous-quote library from today's batch, or null → the caller
// falls back to the app's bundled static pool (see quotes.ts).
export function serverQuotes(): Quote[] | null {
  const q = BATCH && BATCH.quotes;
  return Array.isArray(q) && q.length ? q : null;
}

// Today's fresh mutter pool for a mood (watch/alone/lonely), or null → the brain
// falls back to its built-in MUTTER lines. Zero real-time cost — pre-generated.
export function mutterPool(charId: CharId, mood: MutterMood): string[] | null {
  const c = BATCH && BATCH.cards && BATCH.cards[charId];
  const m = c && c.mutters && c.mutters[mood];
  return Array.isArray(m) && m.length ? m : null;
}

// A shared daily bubble/greeting pool from today's batch, or null → the caller
// falls back to the app's built-in content pack (see content.ts `pool`). `group`
// is a Bubbles field; `key` indexes the nested groups (mutter/speak/routines/hi)
// and is omitted for the flat line pools (poke/retap/drawLines/weaveLines/
// cardHint/sedentary/nightMsg). Returns the batch's own array so its identity
// stays stable across draws — the brain's no-replacement bookkeeping keys on it.
export function bubble(group: string, key?: string): string[] | null {
  const b = BATCH && BATCH.bubbles;
  if (!b) return null;
  const g = (b as Record<string, unknown>)[group];
  const arr = key ? g && (g as Record<string, unknown>)[key] : g;
  return Array.isArray(arr) && arr.length ? (arr as string[]) : null;
}
