// Daily card batch from the server (pre-generated by the Worker's cron).
// Draws pick from this pool locally — no real-time LLM call. When the server
// isn't configured or is unreachable, the pools stay null and callers fall back
// to the built-in offline content in the language packs.
import { lang } from './locale';
import type { CardsBatch, CharId, Lang, MutterMood } from './types';

const pp = window.pp;

let BATCH: CardsBatch | null = null;
let batchLang: Lang | null = null;

export async function refresh(): Promise<CardsBatch | null> {
  if (!pp || !pp.cards) return null;
  const want = lang();
  try {
    const data = await pp.cards.today(want);
    if (data && data.cards) {
      BATCH = data;
      batchLang = want;
    }
  } catch (e) {
    // keep whatever we had (possibly null) — draws just use the local pool
  }
  // a language switch mid-flight (or a failed fetch after one) leaves a
  // wrong-language batch behind — drop it so draws fall back to built-ins
  // rather than handing out cards in the old language
  if (BATCH && batchLang !== lang()) {
    BATCH = null;
    batchLang = null;
  }
  return BATCH;
}

// Date stamp of the loaded batch, or null before the first successful fetch.
// The app compares it across draws to reset its no-replacement bookkeeping
// when a fresh daily pool arrives.
export function batchDate(): string | null {
  return (BATCH && BATCH.date) || null;
}

function poolOf(charId: CharId, tier: 'normal' | 'golden'): string[] | null {
  const c = BATCH && BATCH.cards && BATCH.cards[charId];
  const arr = c && c[tier];
  return Array.isArray(arr) && arr.length ? arr : null;
}

// Today's normal-card lines — one shared voice-neutral pool for every
// character, or null → use the built-in DAILY. Falls back to the per-character
// field an older cached batch may still carry.
export function normalPool(charId: CharId): string[] | null {
  const shared = BATCH && BATCH.normal;
  if (Array.isArray(shared) && shared.length) return shared;
  return poolOf(charId, 'normal');
}

// Today's golden-tier lines, used as the fallback when the personalized weave
// can't reach the LLM (offline or over the daily budget).
export function goldenPool(charId: CharId): string[] | null {
  return poolOf(charId, 'golden');
}

// Today's fresh mutter pool for a mood (watch/alone/lonely), or null → the brain
// falls back to its built-in MUTTER lines. Zero real-time cost — pre-generated.
export function mutterPool(charId: CharId, mood: MutterMood): string[] | null {
  const c = BATCH && BATCH.cards && BATCH.cards[charId];
  const m = c && c.mutters && c.mutters[mood];
  return Array.isArray(m) && m.length ? m : null;
}
